# Generated by Django 5.0.3 on 2024-03-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista_clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
