# Generated by Django 5.0.3 on 2024-03-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sectors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_clientes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes'),
        ),
    ]
