# Generated by Django 5.0.3 on 2024-03-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sectors', '0003_lista_clientes_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_clientes',
            name='foto',
        ),
    ]
